name: Docker TEST
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Available platforms
        run:  echo ${{steps.buildx.outputs.platforms}}
      -
        name: Build and push
        run:  /
          docker login - u ${{secrets.DOCKERHUB.USERNAME}} -p ${{secrets.DOCKERHUB.PASSWORD}}
          docker buildx ls
          docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t lyhuangj/flask-redis:latest .